title: April's Notes
author: April Wang
email: wangqiuoe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some simple notes and instant inspiration while working and studing
# social links
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
